"""Guardrail integration — LiteLLM config generation and OpenClaw config patching.

Generates ~/.defenseclaw/litellm_config.yaml from guardrail settings and
patches ~/.openclaw/openclaw.json to route LLM traffic through LiteLLM.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
from pathlib import Path
from typing import Any

import yaml


def generate_litellm_config(
    model: str,
    model_name: str,
    api_key_env: str,
    port: int,
    device_key_file: str,
) -> dict[str, Any]:
    """Build the LiteLLM proxy config dict."""
    master_key = _derive_master_key(device_key_file)
    return {
        "model_list": [
            {
                "model_name": model_name,
                "litellm_params": {
                    "model": model,
                    "api_key": f"os.environ/{api_key_env}",
                },
            },
        ],
        "general_settings": {
            "master_key": master_key,
        },
        "guardrails": [
            {
                "guardrail_name": "defenseclaw-pre",
                "litellm_params": {
                    "guardrail": "defenseclaw_guardrail.DefenseClawGuardrail",
                    "mode": "pre_call",
                    "default_on": True,
                },
            },
            {
                "guardrail_name": "defenseclaw-post",
                "litellm_params": {
                    "guardrail": "defenseclaw_guardrail.DefenseClawGuardrail",
                    "mode": "post_call",
                    "default_on": True,
                },
            },
        ],
    }


def write_litellm_config(config: dict[str, Any], path: str) -> None:
    """Write the generated LiteLLM config to disk."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("# Auto-generated by DefenseClaw — do not edit manually.\n")
        f.write("# Regenerate with: defenseclaw setup guardrail\n\n")
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)


def patch_openclaw_config(
    openclaw_config_file: str,
    model_name: str,
    litellm_port: int,
    master_key: str,
    original_model: str,
) -> str | None:
    """Patch openclaw.json to route through LiteLLM. Returns the original model or None on error."""
    path = _expand(openclaw_config_file)

    try:
        with open(path) as f:
            cfg = json.load(f)
    except (OSError, json.JSONDecodeError):
        return None

    _backup(path)

    prev_model = (
        cfg.get("agents", {}).get("defaults", {}).get("model", {}).get("primary", "")
    )

    if "models" not in cfg:
        cfg["models"] = {}
    if "providers" not in cfg["models"]:
        cfg["models"]["providers"] = {}

    cfg["models"]["providers"]["litellm"] = {
        "baseUrl": f"http://localhost:{litellm_port}",
        "apiKey": master_key,
        "api": "openai-completions",
        "models": [
            {
                "id": model_name,
                "name": f"{model_name} (via DefenseClaw)",
                "reasoning": False,
                "input": ["text", "image"],
                "contextWindow": 200000,
                "maxTokens": 64000,
            },
        ],
    }

    cfg.setdefault("agents", {}).setdefault("defaults", {}).setdefault("model", {})
    cfg["agents"]["defaults"]["model"]["primary"] = f"litellm/{model_name}"

    with open(path, "w") as f:
        json.dump(cfg, f, indent=2, ensure_ascii=False)
        f.write("\n")

    return prev_model or original_model


def restore_openclaw_config(openclaw_config_file: str, original_model: str) -> bool:
    """Revert OpenClaw config to use the original model directly."""
    path = _expand(openclaw_config_file)

    try:
        with open(path) as f:
            cfg = json.load(f)
    except (OSError, json.JSONDecodeError):
        return False

    _backup(path)

    if original_model:
        cfg.setdefault("agents", {}).setdefault("defaults", {}).setdefault("model", {})
        cfg["agents"]["defaults"]["model"]["primary"] = original_model

    providers = cfg.get("models", {}).get("providers", {})
    providers.pop("litellm", None)

    with open(path, "w") as f:
        json.dump(cfg, f, indent=2, ensure_ascii=False)
        f.write("\n")

    return True


def install_guardrail_module(repo_source: str, target_dir: str) -> bool:
    """Copy the guardrail Python module to the target directory."""
    os.makedirs(target_dir, exist_ok=True)
    dest = os.path.join(target_dir, "defenseclaw_guardrail.py")

    if os.path.isfile(repo_source):
        shutil.copy2(repo_source, dest)
        return True

    return False


def detect_current_model(openclaw_config_file: str) -> tuple[str, str]:
    """Read the current model from openclaw.json. Returns (model_id, provider_prefix)."""
    path = _expand(openclaw_config_file)
    try:
        with open(path) as f:
            cfg = json.load(f)
    except (OSError, json.JSONDecodeError):
        return "", ""

    primary = (
        cfg.get("agents", {}).get("defaults", {}).get("model", {}).get("primary", "")
    )
    if "/" in primary:
        provider, model_id = primary.split("/", 1)
        return primary, provider
    return primary, ""


def detect_api_key_env(model: str) -> str:
    """Guess the API key env var from the model string."""
    lower = model.lower()
    if "anthropic" in lower or "claude" in lower:
        return "ANTHROPIC_API_KEY"
    if "openai" in lower or "gpt" in lower or "o1" in lower:
        return "OPENAI_API_KEY"
    if "gemini" in lower or "google" in lower:
        return "GOOGLE_API_KEY"
    if "bedrock" in lower:
        return "AWS_ACCESS_KEY_ID"
    return "LLM_API_KEY"


def model_to_litellm_name(model: str) -> str:
    """Derive a short LiteLLM model name from a full model string like 'anthropic/claude-opus-4-5'."""
    name = model.split("/")[-1] if "/" in model else model
    for prefix in ("anthropic-", "openai-", "google-"):
        name = name.removeprefix(prefix)
    return name


# ------------------------------------------------------------------
# Internal helpers
# ------------------------------------------------------------------

def _derive_master_key(device_key_file: str) -> str:
    """Derive a deterministic master key from the device key file."""
    path = _expand(device_key_file)
    try:
        with open(path, "rb") as f:
            data = f.read()
        digest = hashlib.sha256(data).hexdigest()[:16]
        return f"sk-dc-{digest}"
    except OSError:
        return "sk-dc-local-dev"


def _expand(p: str) -> str:
    if p.startswith("~/"):
        return str(Path.home() / p[2:])
    return p


def _backup(path: str) -> None:
    """Create a numbered backup of a file."""
    if not os.path.isfile(path):
        return
    bak = path + ".bak"
    if os.path.exists(bak):
        for i in range(1, 20):
            candidate = f"{path}.bak.{i}"
            if not os.path.exists(candidate):
                bak = candidate
                break
    shutil.copy2(path, bak)
