receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318

processors:
  batch:
    send_batch_size: 512
    timeout: 5s

exporters:
  otlp/splunk:
    endpoint: ingest.${env:SPLUNK_REALM}.signalfx.com:443
    headers:
      X-SF-TOKEN: ${env:SPLUNK_ACCESS_TOKEN}
    tls:
      insecure: false

  signalfx:
    access_token: ${env:SPLUNK_ACCESS_TOKEN}
    realm: ${env:SPLUNK_REALM}

  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/splunk]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [signalfx]
